config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'

  resources :entries
  root to: "entries#index"
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :meal_type, :food_item, presence: true

  def day
    created_at.to_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :food_item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="column is-centered mt-6">
  <div class="column is-half is-offset-one-quarter">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">
        Entries for <%= day %>
      </h3>

      <nav class="level is-mobile has-text-centered">
        <div class="level-item">
          <div>
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum %> kcal</p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Proteins</p>
            <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>
        <div class="level-item">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>

      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card mb-4">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br>
              <%= entry.calories %> kcal calories,
              <%= entry.proteins %>g proteins, 
              <%= entry.carbohydrates %>g carbohydrates,
              <%= entry.fats %>g fats
              <!-- Add other entry details here if needed -->
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="actions">
  
  <%= link_to "Back to entries", entries_path, class: "button is-success" %>
  
  
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

  <p>
    <strong>Food item:</strong>
    <%= entry.food_item %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <div class-"message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block", class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block", class: "label"%>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block", class: "label" %>
    <%= form.number_field :proteins, class: "input"%>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block",class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block", class: "label"%>
    <%= form.number_field :fats, class: "input"%>
  </div>

  <div>
    <%= form.label :food_item, style: "display: block", class: "label" %>
    <%= form.text_field :food_item, class: "input"%>
  </div>
  </br>
  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third"> 

    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Entry</h1>

    <%= render "form", entry: @entry %>

  </div>
</div>
<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  <p class="title">FoodLog Application</p> <%= Time.now.strftime("%A %d, %Y") %>
<% end %>

<div id="entries" class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
  <div class="column is-one-quarter">
  <header class="subtitle has-text-weight=bold">
    <%= entry.meal_type %>
  </header>
  <div class="card-content">
    <div class="content">
      <%= render entry %>
      <p class="italic"> Logged <%= time_ago_in_words(entry.created_at)%> ago </p>
    </div>
    </div>
  </div>
  <div class="card-footer">
    <p>
      <%= link_to "Show this entry", entry %>      
    </p>
    
    </div>
  <% end %>
</div>

<div class="actions">
  <%= link_to "New entry", new_entry_path, class: "button is-success" %>
</div>
</br>
<div class="actions">
  <%= link_to "All Entries", archives_index_path, class: "button is-link is-outlined is-centered"  %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third"> 

    <h1 class="is-size-2 has-text-weight-bold mb-3">New Entry</h1>

    <%= render "form", entry: @entry %>

  </div>
</div>
<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <p class="title"><%= @entry.meal_type%></p> <%= Time.now.strftime("%A %d, %Y") %>
<% end %>

<%= render @entry %>

</br>
<div class="actions">
  <%= link_to "Edit this entry", edit_entry_path(@entry), class: "button is-success"%> |
  <%= link_to "Back to entries", entries_path, class: "button is-grey" %>
  </br>
  <%= button_to "Destroy this entry", @entry, method: :delete, class: "button is-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodLog Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/header" %>
  <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
  <% end %> 
  <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
  <% end %> 
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <% if content_for?(:title) %>
  <%= yield(:title) %>
<% else %>
  <p class="title">FoodLog Application</p>
<% end %>
  
  </div>
</section>